---
title: "Isabela & Yuri"
site: distill::distill_website
---

<style type="text/css">
.slick-initialized .slick-slide {
    padding: 0;
}
</style>

<style type="text/css">
h1{
font-family: Taviraj;
}
</style>

<style type="text/css">
h2{
font-family: Taviraj;
}
</style>

<style type="text/css">
h3{
text-align: center;
font-family: Taviraj;
}
</style>

<style type="text/css">
h4{
font-family: Taviraj;
text-align: center;
font-size: 23px;
}
</style>


<style type="text/css">
a{
font-size: 17px;
font-family: Taviraj;
}
</style>

<style type="text/css">
.navbar-fixed-top{
position: absolute;
z-index: 2;
}
</style>

<style type="text/css">
  .navbar-brand {
    min-height: auto;
    content:url("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/sakura_complete_2.png");
    width:100%; /*width of your image*/
    max-width: 100%;
    margin-top: -5%;
    top: 0px;
   height:auto; /*height of your image*/
   padding = 0;
  }
}
</style>

<style type="text/css">
   .title{
   font-size: 0px !important;
}
</style>

<style type="text/css">
   .my_text{
   text-align: center;
   font-family: Taviraj;
}
</style>

<style type="text/css">
   img{
   padding: 3px;
   display:inline-block;
   position: relative;
   top: 0px;
}
</style>

<style type="text/css">
   .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: auto;
}
</style>

<style type="text/css">
   .navbar .navbar-default  .navbar-fixed-top {
  min-height: auto;
  bottom: 0;
}
</style>

<style type="text/css">
  body{
  padding-top: 18%;
}
</style>
<style type="text/css">
@media only screen and (max-width: 768px) {
    body{
  padding-top: 40%;
}
}
</style>

----


### Nós nos casamos oficialmente no dia 05 de abril de 2023 em um cartório de Brasília.

</br>

### Como tínhamos acabado de voltar do Japão após a conclusão de nossos cursos de doutorado e precisávamos começar a organizar logo em seguida nossa mudança para a França, não tivemos tempo para celebrar o casamento com todos os amigos e familiares.

</br>

### Portanto, vamos celebrar nosso casamento no dia 17 de agosto de 2024 com uma cerimônia simbólica seguida de uma festa com jantar.

</br>

### Essa será uma grande oportunidade que teremos de juntar todos nossos amigos e familiares pela primeira vez em uma celebração. Por isso, estamos muito felizes e ansiosos de poder compartilhar esse momento especial com nossos entes queridos.

</br>

### Ficaremos muito felizes e gratos pela sua presença na celebração do nosso casamento!

</br>

----

#### *We got married officially on April 5, 2023, at a registry office in Brasília.*

</br>

#### *As we had just returned from Japan after completing our PhD courses and needed to start organizing our move to France straight away, we didn't have time to celebrate the wedding with all our friends and family.*

</br>

#### *Therefore, we will celebrate our wedding on August 17, 2024, with a symbolic ceremony followed by a dinner party.*

</br>

#### *This will be a great opportunity for us to bring all our friends and family together for the first time in a celebration. Therefore, we are very happy and excited to be able to share this special moment with our loved ones.*

</br>

#### *We will be very happy and grateful for your presence at our wedding celebration!*

----

