---
title: "Isabela & Yuri"
site: distill::distill_website
---

<style type="text/css">
.slick-initialized .slick-slide {
    padding: 0;
}
</style>

<style type="text/css">
h1{
font-family: Taviraj;
}
</style>

<style type="text/css">
h2{
font-family: Taviraj;
}
</style>

<style type="text/css">
h3{
text-align: center;
font-family: Taviraj;
}
</style>

<style type="text/css">
h4{
font-family: Taviraj;
text-align: center;
font-size: 23px;
}
</style>


<style type="text/css">
a{
font-size: 17px;
font-family: Taviraj;
}
</style>

<style type="text/css">
.navbar-fixed-top{
position: absolute;
z-index: 2;
}
</style>

<style type="text/css">
  .navbar-brand {
    min-height: auto;
    content:url("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/sakura_complete_2.png");
    width:100%; /*width of your image*/
    max-width: 100%;
    margin-top: -5%;
    top: 0px;
   height:auto; /*height of your image*/
   padding = 0;
  }
}
</style>

<style type="text/css">
   .title{
   font-size: 0px !important;
}
</style>

<style type="text/css">
   .my_text{
   text-align: center;
   font-family: Taviraj;
}
</style>

<style type="text/css">
   img{
   padding: 3px;
   display:inline-block;
   position: relative;
   top: 0px;
}
</style>

<style type="text/css">
   .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: auto;
}
</style>

<style type="text/css">
   .navbar .navbar-default  .navbar-fixed-top {
  min-height: auto;
  bottom: 0;
}
</style>

<style type="text/css">
  body{
  padding-top: 23%;
}
</style>


<style type="text/css">
@media screen and (-webkit-min-device-pixel-ratio:0)
    body{
  padding-top: 30%;
}
</style>

<style type="text/css">
@media all and (-webkit-min-device-pixel-ratio:0) and (min-resolution: .001dpcm) { 
  body{
  padding-top: 30%;
}
}
</style>


<div style="width: 100%;  position:relative; z-index: 1">
<center class="center">
```{r fig.align='center', echo = FALSE, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::p(
    href=url,
    htmltools::img(src=image,width='70%',...),
    target="_blank"
    )
}
image_link("Abri2022_2.jpeg","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/Abri2022.jpeg")
```

### Data: 17 de agosto de 2024 - Sábado
#### *Date: August 17, 2024 - Saturday*
</div>

</br>

### Horário: 16:30
#### *Time: 4:30 pm*

</br>

### Local (*Location*): Clube do Congresso, Lago Norte - Brasília
### Endereço: SHIN QI 16 Área Especial -  71530-200
#### *Address: SHIN QI 16 Área Especial - 71530-200 - Brasilia, DF, Brazil*
### Localização no Google Maps/Google Maps *Location*:

#### [https://maps.app.goo.gl/R18c3zwySMo9rmeP8/](https://maps.app.goo.gl/R18c3zwySMo9rmeP8/){target="_blank"}


</br>

### Traje: Esporte Fino
#### *Attire: Semi-Formal*

</br>


#### *Please RSVP and confirm your [attendance](https://isabela-yuri.github.io/presenca.html) until June 15th*

</br>

### Se você tiver alguma dúvida, por favor entre em contato conosco
#### *If you have any questions, please reach out to us*


</center>
</div>
