---
title: "Isabela & Yuri"
site: distill::distill_website
---

<style type="text/css">
.slick-initialized .slick-slide {
    padding: 0;
}
</style>

<style type="text/css">
h1{
font-family: Taviraj;
}
</style>

<style type="text/css">
h2{
font-family: Taviraj;
}
</style>

<style type="text/css">
h3{
text-align: center;
font-family: Taviraj;
}
</style>

<style type="text/css">
h4{
font-family: Taviraj;
text-align: center;
font-size: 23px;
}
</style>


<style type="text/css">
a{
font-size: 17px;
font-family: Taviraj;
}
</style>

<style type="text/css">
.navbar-fixed-top{
position: absolute;
z-index: 2;
}
</style>

<style type="text/css">
  .navbar-brand {
    min-height: auto;
    content:url("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/sakura_complete_2.png");
    width:100%; /*width of your image*/
    max-width: 100%;
    margin-top: -5%;
    top: 0px;
   height:auto; /*height of your image*/
   padding = 0;
  }
}
</style>

<style type="text/css">
   .title{
   font-size: 0px !important;
}
</style>

<style type="text/css">
   .my_text{
   text-align: center;
   font-family: Taviraj;
}
</style>

<style type="text/css">
   img{
   padding: 3px;
   display:inline-block;
   position: relative;
   top: 0px;
}
</style>

<style type="text/css">
   .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-top: auto;
}
</style>

<style type="text/css">
   .navbar .navbar-default  .navbar-fixed-top {
  min-height: auto;
  bottom: 0;
}
</style>

<style type="text/css">
  body{
  padding-top: 18%;
}
</style>
<style type="text/css">
@media only screen and (max-width: 768px) {
    body{
  padding-top: 40%;
}
}
</style>

----


### Por favor, confirme a sua presença e a do(s) seu(s) acompanhante(s) através do formulário Google (*link abaixo*) até 15 de abril.
### Por favor, clique no link e para preencher o formulário, é só escrever as sua respostas e depois clicar no botão "Enviar" que aparece no final da página.

</br>

### [https://forms.gle/KYVbFAnmzT5wFMrNA](https://forms.gle/KYVbFAnmzT5wFMrNA){target="_blank"}

</br>

### Ficaremos muito felizes com a sua presença na nossa celebração!

----

#### *Please RSVP and confirm your attendance (and who is accompanying you) using the Google form (*link below*) by April 15th.*
#### *Please, click on the link and to fill out the form, write your answers and then click on "Submit", that appears at the bottom of the page.*
</br>


### [https://forms.gle/fghVKaSAdP42F5JJ6](https://forms.gle/fghVKaSAdP42F5JJ6){target="_blank"}

</br>

#### *We will be very happy to have you at our celebration!*

----
