---
title: "Isabela & Yuri"
site: distill::distill_website
---
</br>
----

<style type="text/css">
.slick-initialized .slick-slide {
    padding: 0;
}
</style>

<style type="text/css">
h1{
font-family: Taviraj;
}
</style>

<style type="text/css">
h2{
font-family: Taviraj;
}
</style>

<style type="text/css">
h3{
font-family: Taviraj;
</br>
}
</style>


<style type="text/css">
a{
font-size: 17px;
font-family: Taviraj;
}
</style>

<style type="text/css">
.navbar-fixed-top{
position: fixed;
}
</style>

<style type="text/css">
  .navbar-brand {
    content:url(https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/imgs/sakura_complete_2.png);
    width:100%; /*width of your image*/
    max-width: 100%;
   height:auto; /*height of your image*/
  }
}
</style>

<style type="text/css">
   .title{
   font-size: 0px !important;;
}
</style>


<style type="text/css">
img{
padding: 3px;
}
</style>

<style  type="text/css">
.col-12 display: block;
position: fixed;
width: 100%;
left: 0;
</style>

</br>

```{r, echo = FALSE}
# Set up the hook
knit_hooks$set(optipng = hook_optipng)
knit_hooks$set(pngquant = hook_pngquant)
```

<center>
<!-- <div> -->
```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04476.jpg","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04476.jpg")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04079.jpg","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04079.jpg")
```

```{r fig.align='right', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04554.jpg","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04554.jpg")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5291.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5291.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5573.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5573.JPG")
```

```{r fig.align='right', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5335.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5335.JPG")
```


```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5499.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5499.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5533.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5533.JPG")
```

```{r fig.align='right', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='33%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5595.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5595.JPG")
```


```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5676.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5676.JPG")
```

```{r fig.align='right', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5509.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5509.JPG")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5142.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5142.JPG")
```


```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5651.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5651.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5212.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5212.JPG")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5325.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5325.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5474.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5474.JPG")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5715.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5715.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5792.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5792.JPG")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5173.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5173.JPG")
```

```{r fig.align='center', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5778.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5778.JPG")
```

```{r fig.align='left', echo = FALSE, cache = FALSE, dpi = 25, optipng = '-o7'}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='49%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5797.JPG","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC_5797.JPG")
```
<!-- </div> -->
</center>