---
title: "Isabela & Yuri"
site: distill::distill_website
---
<style type="text/css">
.slick-initialized .slick-slide {
    padding: 0;
}
</style>

<style type="text/css">
h1{
font-family: Taviraj;
}
</style>

<style type="text/css">
h2{
font-family: Taviraj;
}
</style>

<style type="text/css">
h3{
text-align: center;
font-family: Taviraj;
}
</style>

<style type="text/css">
h4{
font-family: Taviraj;
text-align: center;
font-size: 23px;
}
</style>


<style type="text/css">
a{
font-size: 17px;
font-family: Taviraj;
}
</style>

<style type="text/css">
.navbar-fixed-top{
position: fixed;
}
</style>

<style type="text/css">
  .navbar-brand {
    content:url(https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/imgs/sakura_complete_2.png);
    width:100%; /*width of your image*/
    max-width: 100%;
   height:auto; /*height of your image*/
  }
}
</style>

<style type="text/css">
   .title{
   font-size: 0px !important;
}
</style>

<style type="text/css">
   .my_text{
   text-align: center;
   font-family: Taviraj;
}
</style>

<style type="text/css">
   img{
   ;
}
</style>


<center>
```{r fig.align='center', echo = FALSE}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,width='50%',...),
    target="_blank"
    )
}
image_link("https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04357.jpg","https://media.githubusercontent.com/media/isabela-yuri/isabela-yuri.github.io/main/6bc7410d1d5c571c49960a66fb96a54a856e3fb3/fotos/DSC04357.jpg")
```
</center>
<!-- ,width='50%' -->

</br>
</br>

<div>

### Data: 17 de agosto de 2024 - sábado.
#### *Date: August 17, 2024 - Saturday.*

</br>

### Horário: início da cerimônia às 16:30 – a confirmar.
#### *Time: ceremony starts at 4:30 pm – to be confirmed.*

</br>

### Local (Location): Clube do Congresso, Lago Norte - Brasília.
### Endereço: SHIN QI 16 Área Especial -  71530-200.
#### *Address: SHIN QI 16 Área Especial - 71530-200 - Brasilia, DF, Brazil*
### Localização no Google Maps/Google Maps localization:

#### [https://maps.app.goo.gl/R18c3zwySMo9rmeP8/](https://maps.app.goo.gl/R18c3zwySMo9rmeP8/){target="_blank"}

</br>

### Traje: Esporte Fino
#### *Attire: Semi-Formal*

</br>

### Por favor confirme sua presença até dia 15 de abril.
#### *Please RSVP and confirm your attendance until April 15th.*

</br>

### Se você tiver alguma dúvida, por favor entre em contato conosco.
#### *If you have any questions, please reach out to us.*

</div>